package com.xml.converter.parser;

public class XmlConst {

    public static String xml_1 = "<?xml version=\"1.0\" encoding=\"utf-8\"?>" +
            "<LyncDiagnostics Version=\"string\">\n" +
            "  <ConnectionInfo Originator=\"string\">\n" +
            "    <CallId>string in first callId tag</CallId>\n" +
            "    <!--Optional:-->\n" +
            "    <CorrelationId>string</CorrelationId>\n" +
            "    <!--Optional:-->\n" +
            "    <CSEQ>string</CSEQ>\n" +
            "    <!--Optional:-->\n" +
            "    <ConversationId>string</ConversationId>\n" +
            "    <!--Optional:-->\n" +
            "    <ConferenceId>string</ConferenceId>\n" +
            "    <!--Optional:-->\n" +
            "    <TimeStamp>2008-09-29T04:49:45</TimeStamp>\n" +
            "    <!--Optional:-->\n" +
            "    <Connectivity>string</Connectivity>\n" +
            "    <!--Optional:-->\n" +
            "    <StartTime>2014-09-19T02:18:33</StartTime>\n" +
            "    <!--Optional:-->\n" +
            "    <EndTime>2006-08-19T20:27:14+03:00</EndTime>\n" +
            "    <!--Optional:-->\n" +
            "    <ConferenceURI>http://www.any.com/circum/regemque</ConferenceURI>\n" +
            "    <!--Optional:-->\n" +
            "    <MediaBypass>true</MediaBypass>\n" +
            "    <!--Optional:-->\n" +
            "    <MediationServerLegPosition>string</MediationServerLegPosition>\n" +
            "    <!--Optional:-->\n" +
            "    <SourcePool>string</SourcePool>\n" +
            "  </ConnectionInfo>\n" +
            "  <!--You have a CHOICE of the next 8 items at this level-->\n" +
            "  <Invite>\n" +
            "    <Caller>\n" +
            "      <!--Optional:-->\n" +
            "      <Id>string</Id>\n" +
            "      <!--Optional:-->\n" +
            "      <EPId>string</EPId>\n" +
            "      <URI>http://www.my.com/ferant/profundum</URI>\n" +
            "      <!--Optional:-->\n" +
            "      <Contact>http://www.corp.com/turbine/iovis</Contact>\n" +
            "      <!--Optional:-->\n" +
            "      <IP>string</IP>\n" +
            "      <!--Optional:-->\n" +
            "      <Port>7</Port>\n" +
            "      <!--Optional:-->\n" +
            "      <EPType>string</EPType>\n" +
            "      <!--Optional:-->\n" +
            "      <Relay>anyType</Relay>\n" +
            "      <!--Optional:-->\n" +
            "      <RelayPort>anyType</RelayPort>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexiveIP>anyType</ReflexiveIP>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexivePort>anyType</ReflexivePort>\n" +
            "      <!--Optional:-->\n" +
            "      <UserAgent>string</UserAgent>\n" +
            "      <!--Optional:-->\n" +
            "      <IncallEnabled>true</IncallEnabled>\n" +
            "    </Caller>\n" +
            "    <Callee>\n" +
            "      <!--Optional:-->\n" +
            "      <Id>string</Id>\n" +
            "      <!--Optional:-->\n" +
            "      <EPId>string</EPId>\n" +
            "      <URI>http://www.sample.com/bella/nubibus</URI>\n" +
            "      <!--Optional:-->\n" +
            "      <Contact>http://www.corp.gov/hoc/rapidum</Contact>\n" +
            "      <!--Optional:-->\n" +
            "      <IP>string</IP>\n" +
            "      <!--Optional:-->\n" +
            "      <Port>7</Port>\n" +
            "      <!--Optional:-->\n" +
            "      <EPType>string</EPType>\n" +
            "      <!--Optional:-->\n" +
            "      <Relay>anyType</Relay>\n" +
            "      <!--Optional:-->\n" +
            "      <RelayPort>anyType</RelayPort>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexiveIP>anyType</ReflexiveIP>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexivePort>anyType of ReflexivePort</ReflexivePort>\n" +
            "      <!--Optional:-->\n" +
            "      <UserAgent>string</UserAgent>\n" +
            "      <!--Optional:-->\n" +
            "      <IncallEnabled>false</IncallEnabled>\n" +
            "    </Callee>\n" +
            "  </Invite>\n" +
            "  <Bye>\n" +
            "    <!--0 to 2 repetitions:-->\n" +
            "    <EndPoint>\n" +
            "      <!--Optional:-->\n" +
            "      <Id>string</Id>\n" +
            "      <!--Optional:-->\n" +
            "      <EPId>string</EPId>\n" +
            "      <URI>http://www.my.org/circum/aris</URI>\n" +
            "      <!--Optional:-->\n" +
            "      <Contact>http://www.sample.org/arce/claustra</Contact>\n" +
            "      <!--Optional:-->\n" +
            "      <IP>string</IP>\n" +
            "      <!--Optional:-->\n" +
            "      <Port>7</Port>\n" +
            "      <!--Optional:-->\n" +
            "      <EPType>string</EPType>\n" +
            "      <!--Optional:-->\n" +
            "      <Relay>anyType</Relay>\n" +
            "      <!--Optional:-->\n" +
            "      <RelayPort>anyType</RelayPort>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexiveIP>anyType</ReflexiveIP>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexivePort>anyType</ReflexivePort>\n" +
            "      <!--Optional:-->\n" +
            "      <UserAgent>string</UserAgent>\n" +
            "      <!--Optional:-->\n" +
            "      <IncallEnabled>false</IncallEnabled>\n" +
            "    </EndPoint>\n" +
            "  </Bye>\n" +
            "  <InCallQuality Type=\"string\">\n" +
            "    <From>\n" +
            "      <!--Optional:-->\n" +
            "      <Id>string</Id>\n" +
            "      <!--Optional:-->\n" +
            "      <EPId>string</EPId>\n" +
            "      <URI>http://www.any.com/quisquam/et</URI>\n" +
            "      <!--Optional:-->\n" +
            "      <Contact>http://www.sample.gov/ac/sed</Contact>\n" +
            "      <!--Optional:-->\n" +
            "      <IP>string</IP>\n" +
            "      <!--Optional:-->\n" +
            "      <Port>7</Port>\n" +
            "      <!--Optional:-->\n" +
            "      <EPType>string</EPType>\n" +
            "      <!--Optional:-->\n" +
            "      <Relay>anyType</Relay>\n" +
            "      <!--Optional:-->\n" +
            "      <RelayPort>anyType</RelayPort>\n" +
            "      <!--Optional:-->\n" +
            "      <Inside>false</Inside>\n" +
            "      <!--Optional:-->\n" +
            "      <VPN>true</VPN>\n" +
            "      <!--Optional:-->\n" +
            "      <Connection>string</Connection>\n" +
            "      <!--Optional:-->\n" +
            "      <BSSID>anyType</BSSID>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexiveIP>anyType</ReflexiveIP>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexivePort>anyType</ReflexivePort>\n" +
            "      <!--Optional:-->\n" +
            "      <UserAgent>anyType</UserAgent>\n" +
            "      <!--Optional:-->\n" +
            "      <WifiDriverDeviceDesc>anyType</WifiDriverDeviceDesc>\n" +
            "      <!--Optional:-->\n" +
            "      <WifiDriverVersion>anyType</WifiDriverVersion>\n" +
            "      <!--Optional:-->\n" +
            "      <OS>anyType</OS>\n" +
            "      <!--Optional:-->\n" +
            "      <CPUName>anyType</CPUName>\n" +
            "      <!--Optional:-->\n" +
            "      <CPUNumberOfCores>anyType</CPUNumberOfCores>\n" +
            "      <!--Optional:-->\n" +
            "      <CPUProcessorSpeed>anyType</CPUProcessorSpeed>\n" +
            "      <!--Optional:-->\n" +
            "      <Virtualization>anyType</Virtualization>\n" +
            "      <!--Optional:-->\n" +
            "      <MACAddr>anyType</MACAddr>\n" +
            "      <!--Optional:-->\n" +
            "      <DSCPInbound>anyType</DSCPInbound>\n" +
            "      <!--Optional:-->\n" +
            "      <DSCPOutbound>anyType</DSCPOutbound>\n" +
            "      <!--Optional:-->\n" +
            "      <LinkSpeed>anyType</LinkSpeed>\n" +
            "    </From>\n" +
            "    <To>\n" +
            "      <!--Optional:-->\n" +
            "      <Id>string</Id>\n" +
            "      <!--Optional:-->\n" +
            "      <EPId>string</EPId>\n" +
            "      <URI>http://www.corp.edu/annos/sciret</URI>\n" +
            "      <!--Optional:-->\n" +
            "      <Contact>http://www.corp.com/rates/bella</Contact>\n" +
            "      <!--Optional:-->\n" +
            "      <IP>string</IP>\n" +
            "      <!--Optional:-->\n" +
            "      <Port>7</Port>\n" +
            "      <!--Optional:-->\n" +
            "      <EPType>string</EPType>\n" +
            "      <!--Optional:-->\n" +
            "      <Relay>anyType</Relay>\n" +
            "      <!--Optional:-->\n" +
            "      <RelayPort>anyType</RelayPort>\n" +
            "      <!--Optional:-->\n" +
            "      <Inside>true</Inside>\n" +
            "      <!--Optional:-->\n" +
            "      <VPN>false</VPN>\n" +
            "      <!--Optional:-->\n" +
            "      <Connection>string</Connection>\n" +
            "      <!--Optional:-->\n" +
            "      <BSSID>anyType</BSSID>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexiveIP>anyType</ReflexiveIP>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexivePort>anyType</ReflexivePort>\n" +
            "      <!--Optional:-->\n" +
            "      <UserAgent>anyType</UserAgent>\n" +
            "      <!--Optional:-->\n" +
            "      <WifiDriverDeviceDesc>anyType</WifiDriverDeviceDesc>\n" +
            "      <!--Optional:-->\n" +
            "      <WifiDriverVersion>anyType</WifiDriverVersion>\n" +
            "      <!--Optional:-->\n" +
            "      <OS>anyType</OS>\n" +
            "      <!--Optional:-->\n" +
            "      <CPUName>anyType</CPUName>\n" +
            "      <!--Optional:-->\n" +
            "      <CPUNumberOfCores>anyType</CPUNumberOfCores>\n" +
            "      <!--Optional:-->\n" +
            "      <CPUProcessorSpeed>anyType</CPUProcessorSpeed>\n" +
            "      <!--Optional:-->\n" +
            "      <Virtualization>anyType</Virtualization>\n" +
            "      <!--Optional:-->\n" +
            "      <MACAddr>anyType</MACAddr>\n" +
            "      <!--Optional:-->\n" +
            "      <DSCPInbound>anyType</DSCPInbound>\n" +
            "      <!--Optional:-->\n" +
            "      <DSCPOutbound>anyType</DSCPOutbound>\n" +
            "      <!--Optional:-->\n" +
            "      <LinkSpeed>anyType</LinkSpeed>\n" +
            "    </To>\n" +
            "    <Properties>\n" +
            "      <!--You have a CHOICE of the next 69 items at this level-->\n" +
            "      <StreamQuality>string</StreamQuality>\n" +
            "      <Protocol>string</Protocol>\n" +
            "      <Codec Name=\"string\">\n" +
            "        <!--Optional:-->\n" +
            "        <Bandwidth>string</Bandwidth>\n" +
            "        <!--Optional:-->\n" +
            "        <MaxBandwidth>string</MaxBandwidth>\n" +
            "      </Codec>\n" +
            "      <ConversationalMOS>string</ConversationalMOS>\n" +
            "      <PacketUtilization>string</PacketUtilization>\n" +
            "      <PacketLossRate>anyType</PacketLossRate>\n" +
            "      <PacketLossRateMax>anyType</PacketLossRateMax>\n" +
            "      <JitterInterArrival>anyType</JitterInterArrival>\n" +
            "      <JitterInterArrivalMax>string</JitterInterArrivalMax>\n" +
            "      <RoundTrip>anyType</RoundTrip>\n" +
            "      <RoundTripMax>string</RoundTripMax>\n" +
            "      <HealerPacketDropRatio>string</HealerPacketDropRatio>\n" +
            "      <DegradationAvg>anyType</DegradationAvg>\n" +
            "      <RatioConcealedSamplesAvg>anyType</RatioConcealedSamplesAvg>\n" +
            "      <EchoPercentMicIn>string</EchoPercentMicIn>\n" +
            "      <EchoPercentSend>string</EchoPercentSend>\n" +
            "      <EchoReturn>anyType</EchoReturn>\n" +
            "      <EchoEventCauses>anyType</EchoEventCauses>\n" +
            "      <RecvNoiseLevel>string</RecvNoiseLevel>\n" +
            "      <RecvSignalLevel>string</RecvSignalLevel>\n" +
            "      <BurstDuration>anyType</BurstDuration>\n" +
            "      <BurstDensity>anyType</BurstDensity>\n" +
            "      <BurstGapDuration>string</BurstGapDuration>\n" +
            "      <BurstGapDensity>anyType</BurstGapDensity>\n" +
            "      <DegradationJitterAvg>string</DegradationJitterAvg>\n" +
            "      <DegradationMax>string</DegradationMax>\n" +
            "      <RecvListenMOSMin>anyType</RecvListenMOSMin>\n" +
            "      <SendListenMOSMin>anyType</SendListenMOSMin>\n" +
            "      <SendListenMOS>anyType</SendListenMOS>\n" +
            "      <RecvListenMOS>anyType</RecvListenMOS>\n" +
            "      <OverallMinNetworkMOS>string</OverallMinNetworkMOS>\n" +
            "      <OverallAvgNetworkMOS>string</OverallAvgNetworkMOS>\n" +
            "      <DegradationPacketLossAvg>anyType</DegradationPacketLossAvg>\n" +
            "      <CaptureDevice>anyType</CaptureDevice>\n" +
            "      <CaptureDeviceDriver>anyType</CaptureDeviceDriver>\n" +
            "      <MicGlitchRate>anyType</MicGlitchRate>\n" +
            "      <SpeakerGlitchRate>anyType</SpeakerGlitchRate>\n" +
            "      <RenderDevice>anyType</RenderDevice>\n" +
            "      <RenderDeviceDriver>anyType</RenderDeviceDriver>\n" +
            "      <CPUInsufficientEventRatio>anyType</CPUInsufficientEventRatio>\n" +
            "      <DeviceCaptureNotFunctioningEventRatio>anyType</DeviceCaptureNotFunctioningEventRatio>\n" +
            "      <DeviceRenderNotFunctioningEventRatio>anyType</DeviceRenderNotFunctioningEventRatio>\n" +
            "      <DeviceClippingEventRatio>anyType</DeviceClippingEventRatio>\n" +
            "      <DeviceHowlingEventCount>anyType</DeviceHowlingEventCount>\n" +
            "      <NetworkDelayEventRatio>anyType</NetworkDelayEventRatio>\n" +
            "      <DeviceNearEndToEchoRatioEventRatio>anyType</DeviceNearEndToEchoRatioEventRatio>\n" +
            "      <DeviceEchoEventRatio>anyType</DeviceEchoEventRatio>\n" +
            "      <AudioTimestampErrorMicMs>anyType</AudioTimestampErrorMicMs>\n" +
            "      <AudioTimestampErrorSpkMs>anyType</AudioTimestampErrorSpkMs>\n" +
            "      <VideoPacketLossRate>anyType</VideoPacketLossRate>\n" +
            "      <RecvFrameRateAverage>anyType</RecvFrameRateAverage>\n" +
            "      <VideoLocalFrameLossPercentageAvg>anyType</VideoLocalFrameLossPercentageAvg>\n" +
            "      <DynamicCapabilityPercent>anyType</DynamicCapabilityPercent>\n" +
            "      <LowFrameRateCallPercent>anyType</LowFrameRateCallPercent>\n" +
            "      <LowResolutionCallPercent>anyType</LowResolutionCallPercent>\n" +
            "      <VideoFrameLossRate>anyType</VideoFrameLossRate>\n" +
            "      <LocalFrameLossPercentageAvg>string</LocalFrameLossPercentageAvg>\n" +
            "      <BitRateMax>string</BitRateMax>\n" +
            "      <BitRateAvg>string</BitRateAvg>\n" +
            "      <VGAQualityRatio>anyType</VGAQualityRatio>\n" +
            "      <HDQualityRatio>anyType</HDQualityRatio>\n" +
            "      <RelativeOneWayBurstDensity>anyType</RelativeOneWayBurstDensity>\n" +
            "      <RelativeOneWayAverage>anyType</RelativeOneWayAverage>\n" +
            "      <RDPTileProcessingLatencyBurstDensity>anyType</RDPTileProcessingLatencyBurstDensity>\n" +
            "      <RDPTileProcessingLatencyAverage>anyType</RDPTileProcessingLatencyAverage>\n" +
            "      <SpoiledTilePercentTotal>anyType</SpoiledTilePercentTotal>\n" +
            "      <SpoiledTilePercentAverage>1000.00</SpoiledTilePercentAverage>\n" +
            "      <FrameRate>1000.00</FrameRate>\n" +
            "      <!--Optional:-->\n" +
            "      <AppliedBandwidthLimit>7</AppliedBandwidthLimit>\n" +
            "    </Properties>\n" +
            "    <!--Optional:-->\n" +
            "    <Route>\n" +
            "      <!--1 or more repetitions:-->\n" +
            "      <Hop>string</Hop>\n" +
            "    </Route>\n" +
            "  </InCallQuality>\n" +
            "  <QualityUpdate Type=\"string\">\n" +
            "    <From>\n" +
            "      <!--Optional:-->\n" +
            "      <Id>string</Id>\n" +
            "      <!--Optional:-->\n" +
            "      <EPId>string</EPId>\n" +
            "      <URI>http://www.test.com/et/ac</URI>\n" +
            "      <!--Optional:-->\n" +
            "      <Contact>http://www.any.com/annos/infixit</Contact>\n" +
            "      <!--Optional:-->\n" +
            "      <IP>string</IP>\n" +
            "      <!--Optional:-->\n" +
            "      <Port>7</Port>\n" +
            "      <!--Optional:-->\n" +
            "      <EPType>string</EPType>\n" +
            "      <!--Optional:-->\n" +
            "      <Relay>anyType</Relay>\n" +
            "      <!--Optional:-->\n" +
            "      <RelayPort>anyType</RelayPort>\n" +
            "      <!--Optional:-->\n" +
            "      <Inside>true</Inside>\n" +
            "      <!--Optional:-->\n" +
            "      <VPN>false</VPN>\n" +
            "      <!--Optional:-->\n" +
            "      <Connection>string</Connection>\n" +
            "      <!--Optional:-->\n" +
            "      <BSSID>anyType</BSSID>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexiveIP>anyType</ReflexiveIP>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexivePort>anyType</ReflexivePort>\n" +
            "      <!--Optional:-->\n" +
            "      <UserAgent>anyType</UserAgent>\n" +
            "      <!--Optional:-->\n" +
            "      <WifiDriverDeviceDesc>anyType</WifiDriverDeviceDesc>\n" +
            "      <!--Optional:-->\n" +
            "      <WifiDriverVersion>anyType</WifiDriverVersion>\n" +
            "      <!--Optional:-->\n" +
            "      <OS>anyType</OS>\n" +
            "      <!--Optional:-->\n" +
            "      <CPUName>anyType</CPUName>\n" +
            "      <!--Optional:-->\n" +
            "      <CPUNumberOfCores>anyType</CPUNumberOfCores>\n" +
            "      <!--Optional:-->\n" +
            "      <CPUProcessorSpeed>anyType</CPUProcessorSpeed>\n" +
            "      <!--Optional:-->\n" +
            "      <Virtualization>anyType</Virtualization>\n" +
            "      <!--Optional:-->\n" +
            "      <MACAddr>anyType</MACAddr>\n" +
            "      <!--Optional:-->\n" +
            "      <DSCPInbound>anyType</DSCPInbound>\n" +
            "      <!--Optional:-->\n" +
            "      <DSCPOutbound>anyType</DSCPOutbound>\n" +
            "      <!--Optional:-->\n" +
            "      <LinkSpeed>anyType</LinkSpeed>\n" +
            "    </From>\n" +
            "    <To>\n" +
            "      <!--Optional:-->\n" +
            "      <Id>string</Id>\n" +
            "      <!--Optional:-->\n" +
            "      <EPId>string</EPId>\n" +
            "      <URI>http://www.my.org/rapidum/habenas</URI>\n" +
            "      <!--Optional:-->\n" +
            "      <Contact>http://www.sample.org/cum/iovisque</Contact>\n" +
            "      <!--Optional:-->\n" +
            "      <IP>string</IP>\n" +
            "      <!--Optional:-->\n" +
            "      <Port>7</Port>\n" +
            "      <!--Optional:-->\n" +
            "      <EPType>string</EPType>\n" +
            "      <!--Optional:-->\n" +
            "      <Relay>anyType</Relay>\n" +
            "      <!--Optional:-->\n" +
            "      <RelayPort>anyType</RelayPort>\n" +
            "      <!--Optional:-->\n" +
            "      <Inside>true</Inside>\n" +
            "      <!--Optional:-->\n" +
            "      <VPN>true</VPN>\n" +
            "      <!--Optional:-->\n" +
            "      <Connection>string</Connection>\n" +
            "      <!--Optional:-->\n" +
            "      <BSSID>anyType</BSSID>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexiveIP>anyType</ReflexiveIP>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexivePort>anyType</ReflexivePort>\n" +
            "      <!--Optional:-->\n" +
            "      <UserAgent>anyType</UserAgent>\n" +
            "      <!--Optional:-->\n" +
            "      <WifiDriverDeviceDesc>anyType</WifiDriverDeviceDesc>\n" +
            "      <!--Optional:-->\n" +
            "      <WifiDriverVersion>anyType</WifiDriverVersion>\n" +
            "      <!--Optional:-->\n" +
            "      <OS>anyType</OS>\n" +
            "      <!--Optional:-->\n" +
            "      <CPUName>anyType</CPUName>\n" +
            "      <!--Optional:-->\n" +
            "      <CPUNumberOfCores>anyType</CPUNumberOfCores>\n" +
            "      <!--Optional:-->\n" +
            "      <CPUProcessorSpeed>anyType</CPUProcessorSpeed>\n" +
            "      <!--Optional:-->\n" +
            "      <Virtualization>anyType</Virtualization>\n" +
            "      <!--Optional:-->\n" +
            "      <MACAddr>anyType</MACAddr>\n" +
            "      <!--Optional:-->\n" +
            "      <DSCPInbound>anyType</DSCPInbound>\n" +
            "      <!--Optional:-->\n" +
            "      <DSCPOutbound>anyType</DSCPOutbound>\n" +
            "      <!--Optional:-->\n" +
            "      <LinkSpeed>anyType</LinkSpeed>\n" +
            "    </To>\n" +
            "    <Properties>\n" +
            "      <!--You have a CHOICE of the next 69 items at this level-->\n" +
            "      <StreamQuality>string</StreamQuality>\n" +
            "      <Protocol>string</Protocol>\n" +
            "      <Codec Name=\"string\">\n" +
            "        <!--Optional:-->\n" +
            "        <Bandwidth>string</Bandwidth>\n" +
            "        <!--Optional:-->\n" +
            "        <MaxBandwidth>string</MaxBandwidth>\n" +
            "      </Codec>\n" +
            "      <ConversationalMOS>string</ConversationalMOS>\n" +
            "      <PacketUtilization>string</PacketUtilization>\n" +
            "      <PacketLossRate>anyType</PacketLossRate>\n" +
            "      <PacketLossRateMax>anyType</PacketLossRateMax>\n" +
            "      <JitterInterArrival>anyType</JitterInterArrival>\n" +
            "      <JitterInterArrivalMax>string</JitterInterArrivalMax>\n" +
            "      <RoundTrip>anyType</RoundTrip>\n" +
            "      <RoundTripMax>string</RoundTripMax>\n" +
            "      <HealerPacketDropRatio>string</HealerPacketDropRatio>\n" +
            "      <DegradationAvg>anyType</DegradationAvg>\n" +
            "      <RatioConcealedSamplesAvg>anyType</RatioConcealedSamplesAvg>\n" +
            "      <EchoPercentMicIn>string</EchoPercentMicIn>\n" +
            "      <EchoPercentSend>string</EchoPercentSend>\n" +
            "      <EchoReturn>anyType</EchoReturn>\n" +
            "      <EchoEventCauses>anyType</EchoEventCauses>\n" +
            "      <RecvNoiseLevel>string</RecvNoiseLevel>\n" +
            "      <RecvSignalLevel>string</RecvSignalLevel>\n" +
            "      <BurstDuration>anyType</BurstDuration>\n" +
            "      <BurstDensity>anyType</BurstDensity>\n" +
            "      <BurstGapDuration>string</BurstGapDuration>\n" +
            "      <BurstGapDensity>anyType</BurstGapDensity>\n" +
            "      <DegradationJitterAvg>string</DegradationJitterAvg>\n" +
            "      <DegradationMax>string</DegradationMax>\n" +
            "      <RecvListenMOSMin>anyType</RecvListenMOSMin>\n" +
            "      <SendListenMOSMin>anyType</SendListenMOSMin>\n" +
            "      <SendListenMOS>anyType</SendListenMOS>\n" +
            "      <RecvListenMOS>anyType</RecvListenMOS>\n" +
            "      <OverallMinNetworkMOS>string</OverallMinNetworkMOS>\n" +
            "      <OverallAvgNetworkMOS>string</OverallAvgNetworkMOS>\n" +
            "      <DegradationPacketLossAvg>anyType</DegradationPacketLossAvg>\n" +
            "      <CaptureDevice>anyType</CaptureDevice>\n" +
            "      <CaptureDeviceDriver>anyType</CaptureDeviceDriver>\n" +
            "      <MicGlitchRate>anyType</MicGlitchRate>\n" +
            "      <SpeakerGlitchRate>anyType</SpeakerGlitchRate>\n" +
            "      <RenderDevice>anyType</RenderDevice>\n" +
            "      <RenderDeviceDriver>anyType</RenderDeviceDriver>\n" +
            "      <CPUInsufficientEventRatio>anyType</CPUInsufficientEventRatio>\n" +
            "      <DeviceCaptureNotFunctioningEventRatio>anyType</DeviceCaptureNotFunctioningEventRatio>\n" +
            "      <DeviceRenderNotFunctioningEventRatio>anyType</DeviceRenderNotFunctioningEventRatio>\n" +
            "      <DeviceClippingEventRatio>anyType</DeviceClippingEventRatio>\n" +
            "      <DeviceHowlingEventCount>anyType</DeviceHowlingEventCount>\n" +
            "      <NetworkDelayEventRatio>anyType</NetworkDelayEventRatio>\n" +
            "      <DeviceNearEndToEchoRatioEventRatio>anyType</DeviceNearEndToEchoRatioEventRatio>\n" +
            "      <DeviceEchoEventRatio>anyType</DeviceEchoEventRatio>\n" +
            "      <AudioTimestampErrorMicMs>anyType</AudioTimestampErrorMicMs>\n" +
            "      <AudioTimestampErrorSpkMs>anyType</AudioTimestampErrorSpkMs>\n" +
            "      <VideoPacketLossRate>anyType</VideoPacketLossRate>\n" +
            "      <RecvFrameRateAverage>anyType</RecvFrameRateAverage>\n" +
            "      <VideoLocalFrameLossPercentageAvg>anyType</VideoLocalFrameLossPercentageAvg>\n" +
            "      <DynamicCapabilityPercent>anyType</DynamicCapabilityPercent>\n" +
            "      <LowFrameRateCallPercent>anyType</LowFrameRateCallPercent>\n" +
            "      <LowResolutionCallPercent>anyType</LowResolutionCallPercent>\n" +
            "      <VideoFrameLossRate>anyType</VideoFrameLossRate>\n" +
            "      <LocalFrameLossPercentageAvg>string</LocalFrameLossPercentageAvg>\n" +
            "      <BitRateMax>string</BitRateMax>\n" +
            "      <BitRateAvg>string</BitRateAvg>\n" +
            "      <VGAQualityRatio>anyType</VGAQualityRatio>\n" +
            "      <HDQualityRatio>anyType</HDQualityRatio>\n" +
            "      <RelativeOneWayBurstDensity>anyType</RelativeOneWayBurstDensity>\n" +
            "      <RelativeOneWayAverage>anyType</RelativeOneWayAverage>\n" +
            "      <RDPTileProcessingLatencyBurstDensity>anyType</RDPTileProcessingLatencyBurstDensity>\n" +
            "      <RDPTileProcessingLatencyAverage>anyType</RDPTileProcessingLatencyAverage>\n" +
            "      <SpoiledTilePercentTotal>anyType</SpoiledTilePercentTotal>\n" +
            "      <SpoiledTilePercentAverage>1000.00</SpoiledTilePercentAverage>\n" +
            "      <FrameRate>1000.00</FrameRate>\n" +
            "      <!--Optional:-->\n" +
            "      <AppliedBandwidthLimit>7</AppliedBandwidthLimit>\n" +
            "    </Properties>\n" +
            "    <!--Optional:-->\n" +
            "    <Route>\n" +
            "      <!--1 or more repetitions:-->\n" +
            "      <Hop>string</Hop>\n" +
            "    </Route>\n" +
            "  </QualityUpdate>\n" +
            "  <Error Type=\"string\">\n" +
            "    <!--0 to 2 repetitions:-->\n" +
            "    <EndPoint>\n" +
            "      <!--Optional:-->\n" +
            "      <Id>string</Id>\n" +
            "      <!--Optional:-->\n" +
            "      <EPId>string</EPId>\n" +
            "      <URI>http://www.my.edu/coniunx/adorat</URI>\n" +
            "      <!--Optional:-->\n" +
            "      <Contact>http://www.any.com/frenat/aris</Contact>\n" +
            "      <!--Optional:-->\n" +
            "      <IP>string</IP>\n" +
            "      <!--Optional:-->\n" +
            "      <Port>7</Port>\n" +
            "      <!--Optional:-->\n" +
            "      <EPType>string</EPType>\n" +
            "      <!--Optional:-->\n" +
            "      <Relay>anyType</Relay>\n" +
            "      <!--Optional:-->\n" +
            "      <RelayPort>anyType</RelayPort>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexiveIP>anyType</ReflexiveIP>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexivePort>anyType</ReflexivePort>\n" +
            "      <!--Optional:-->\n" +
            "      <UserAgent>string</UserAgent>\n" +
            "      <!--Optional:-->\n" +
            "      <IncallEnabled>true</IncallEnabled>\n" +
            "    </EndPoint>\n" +
            "    <!--Optional:-->\n" +
            "    <From>\n" +
            "      <!--Optional:-->\n" +
            "      <Id>string</Id>\n" +
            "      <!--Optional:-->\n" +
            "      <EPId>string</EPId>\n" +
            "      <URI>http://www.any.org/premere/montis</URI>\n" +
            "      <!--Optional:-->\n" +
            "      <Contact>http://www.company.edu/ferant/gero</Contact>\n" +
            "      <!--Optional:-->\n" +
            "      <IP>string</IP>\n" +
            "      <!--Optional:-->\n" +
            "      <Port>7</Port>\n" +
            "      <!--Optional:-->\n" +
            "      <EPType>string</EPType>\n" +
            "      <!--Optional:-->\n" +
            "      <Relay>anyType</Relay>\n" +
            "      <!--Optional:-->\n" +
            "      <RelayPort>anyType</RelayPort>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexiveIP>anyType</ReflexiveIP>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexivePort>anyType</ReflexivePort>\n" +
            "      <!--Optional:-->\n" +
            "      <UserAgent>string</UserAgent>\n" +
            "      <!--Optional:-->\n" +
            "      <IncallEnabled>true</IncallEnabled>\n" +
            "    </From>\n" +
            "    <!--Optional:-->\n" +
            "    <To>\n" +
            "      <!--Optional:-->\n" +
            "      <Id>string</Id>\n" +
            "      <!--Optional:-->\n" +
            "      <EPId>string</EPId>\n" +
            "      <URI>http://www.test.org/montis/flammato</URI>\n" +
            "      <!--Optional:-->\n" +
            "      <Contact>http://www.any.gov/aris/tenens</Contact>\n" +
            "      <!--Optional:-->\n" +
            "      <IP>string</IP>\n" +
            "      <!--Optional:-->\n" +
            "      <Port>7</Port>\n" +
            "      <!--Optional:-->\n" +
            "      <EPType>string</EPType>\n" +
            "      <!--Optional:-->\n" +
            "      <Relay>anyType</Relay>\n" +
            "      <!--Optional:-->\n" +
            "      <RelayPort>anyType</RelayPort>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexiveIP>anyType</ReflexiveIP>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexivePort>anyType</ReflexivePort>\n" +
            "      <!--Optional:-->\n" +
            "      <UserAgent>string</UserAgent>\n" +
            "      <!--Optional:-->\n" +
            "      <IncallEnabled>true</IncallEnabled>\n" +
            "    </To>\n" +
            "    <!--Optional:-->\n" +
            "    <Properties>\n" +
            "      <!--Optional:-->\n" +
            "      <ResponseCode>3</ResponseCode>\n" +
            "      <!--Optional:-->\n" +
            "      <ResponsePhrase>string</ResponsePhrase>\n" +
            "      <!--Optional:-->\n" +
            "      <MSDiagnostics>string</MSDiagnostics>\n" +
            "      <!--Optional:-->\n" +
            "      <MSDiagnosticsClient>string</MSDiagnosticsClient>\n" +
            "      <!--Optional:-->\n" +
            "      <MSDiagnosticsPublic>string</MSDiagnosticsPublic>\n" +
            "    </Properties>\n" +
            "  </Error>\n" +
            "  <Ended Type=\"string\">\n" +
            "    <!--0 to 2 repetitions:-->\n" +
            "    <EndPoint>\n" +
            "      <!--Optional:-->\n" +
            "      <Id>string</Id>\n" +
            "      <!--Optional:-->\n" +
            "      <EPId>string</EPId>\n" +
            "      <URI>http://www.test.org/iras/acuto</URI>\n" +
            "      <!--Optional:-->\n" +
            "      <Contact>http://www.any.edu/austris/dedit</Contact>\n" +
            "      <!--Optional:-->\n" +
            "      <IP>string</IP>\n" +
            "      <!--Optional:-->\n" +
            "      <Port>7</Port>\n" +
            "      <!--Optional:-->\n" +
            "      <EPType>string</EPType>\n" +
            "      <!--Optional:-->\n" +
            "      <Relay>anyType</Relay>\n" +
            "      <!--Optional:-->\n" +
            "      <RelayPort>anyType</RelayPort>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexiveIP>anyType</ReflexiveIP>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexivePort>anyType</ReflexivePort>\n" +
            "      <!--Optional:-->\n" +
            "      <UserAgent>string</UserAgent>\n" +
            "      <!--Optional:-->\n" +
            "      <IncallEnabled>false</IncallEnabled>\n" +
            "    </EndPoint>\n" +
            "    <!--Optional:-->\n" +
            "    <From>\n" +
            "      <!--Optional:-->\n" +
            "      <Id>string</Id>\n" +
            "      <!--Optional:-->\n" +
            "      <EPId>string</EPId>\n" +
            "      <URI>http://www.test.com/imposuit/atris</URI>\n" +
            "      <!--Optional:-->\n" +
            "      <Contact>http://www.test.com/iras/sonoras</Contact>\n" +
            "      <!--Optional:-->\n" +
            "      <IP>string</IP>\n" +
            "      <!--Optional:-->\n" +
            "      <Port>7</Port>\n" +
            "      <!--Optional:-->\n" +
            "      <EPType>string</EPType>\n" +
            "      <!--Optional:-->\n" +
            "      <Relay>anyType</Relay>\n" +
            "      <!--Optional:-->\n" +
            "      <RelayPort>anyType</RelayPort>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexiveIP>anyType</ReflexiveIP>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexivePort>anyType</ReflexivePort>\n" +
            "      <!--Optional:-->\n" +
            "      <UserAgent>string</UserAgent>\n" +
            "      <!--Optional:-->\n" +
            "      <IncallEnabled>true</IncallEnabled>\n" +
            "    </From>\n" +
            "    <!--Optional:-->\n" +
            "    <To>\n" +
            "      <!--Optional:-->\n" +
            "      <Id>string</Id>\n" +
            "      <!--Optional:-->\n" +
            "      <EPId>string</EPId>\n" +
            "      <URI>http://www.corp.org/montis/dare</URI>\n" +
            "      <!--Optional:-->\n" +
            "      <Contact>http://www.test.org/e/sceptra</Contact>\n" +
            "      <!--Optional:-->\n" +
            "      <IP>string</IP>\n" +
            "      <!--Optional:-->\n" +
            "      <Port>7</Port>\n" +
            "      <!--Optional:-->\n" +
            "      <EPType>string</EPType>\n" +
            "      <!--Optional:-->\n" +
            "      <Relay>anyType</Relay>\n" +
            "      <!--Optional:-->\n" +
            "      <RelayPort>anyType</RelayPort>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexiveIP>anyType</ReflexiveIP>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexivePort>anyType</ReflexivePort>\n" +
            "      <!--Optional:-->\n" +
            "      <UserAgent>string</UserAgent>\n" +
            "      <!--Optional:-->\n" +
            "      <IncallEnabled>false</IncallEnabled>\n" +
            "    </To>\n" +
            "    <!--Optional:-->\n" +
            "    <Properties>\n" +
            "      <!--Optional:-->\n" +
            "      <MSDiagnostics>string</MSDiagnostics>\n" +
            "      <!--Optional:-->\n" +
            "      <MSDiagnosticsClient>string</MSDiagnosticsClient>\n" +
            "      <!--Optional:-->\n" +
            "      <MSDiagnosticsPublic>string</MSDiagnosticsPublic>\n" +
            "    </Properties>\n" +
            "  </Ended>\n" +
            "  <Start Type=\"string\">\n" +
            "    <!--Optional:-->\n" +
            "    <From>\n" +
            "      <!--Optional:-->\n" +
            "      <Id>string</Id>\n" +
            "      <!--Optional:-->\n" +
            "      <EPId>string</EPId>\n" +
            "      <URI>http://www.corp.com/coniunx/vinclis</URI>\n" +
            "      <!--Optional:-->\n" +
            "      <Contact>http://www.company.org/turbine/antro</Contact>\n" +
            "      <!--Optional:-->\n" +
            "      <IP>string</IP>\n" +
            "      <!--Optional:-->\n" +
            "      <Port>7</Port>\n" +
            "      <!--Optional:-->\n" +
            "      <EPType>string</EPType>\n" +
            "      <!--Optional:-->\n" +
            "      <Relay>anyType</Relay>\n" +
            "      <!--Optional:-->\n" +
            "      <RelayPort>anyType</RelayPort>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexiveIP>anyType</ReflexiveIP>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexivePort>anyType</ReflexivePort>\n" +
            "      <!--Optional:-->\n" +
            "      <UserAgent>string</UserAgent>\n" +
            "      <!--Optional:-->\n" +
            "      <IncallEnabled>true</IncallEnabled>\n" +
            "    </From>\n" +
            "    <!--Optional:-->\n" +
            "    <To>\n" +
            "      <!--Optional:-->\n" +
            "      <Id>string</Id>\n" +
            "      <!--Optional:-->\n" +
            "      <EPId>string</EPId>\n" +
            "      <URI>http://www.sample.org/luctantis/aequora</URI>\n" +
            "      <!--Optional:-->\n" +
            "      <Contact>http://www.sample.org/aris/incedo</Contact>\n" +
            "      <!--Optional:-->\n" +
            "      <IP>string</IP>\n" +
            "      <!--Optional:-->\n" +
            "      <Port>7</Port>\n" +
            "      <!--Optional:-->\n" +
            "      <EPType>string</EPType>\n" +
            "      <!--Optional:-->\n" +
            "      <Relay>anyType</Relay>\n" +
            "      <!--Optional:-->\n" +
            "      <RelayPort>anyType</RelayPort>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexiveIP>anyType</ReflexiveIP>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexivePort>anyType</ReflexivePort>\n" +
            "      <!--Optional:-->\n" +
            "      <UserAgent>string</UserAgent>\n" +
            "      <!--Optional:-->\n" +
            "      <IncallEnabled>false</IncallEnabled>\n" +
            "    </To>\n" +
            "    <!--Optional:-->\n" +
            "    <Properties>\n" +
            "      <Protocol>string</Protocol>\n" +
            "      <!--Optional:-->\n" +
            "      <Bandwidth Multiplexed=\"3\">\n" +
            "        <!--Optional:-->\n" +
            "        <Average>10</Average>\n" +
            "        <!--Optional:-->\n" +
            "        <Maximum>10</Maximum>\n" +
            "      </Bandwidth>\n" +
            "      <!--Zero or more repetitions:-->\n" +
            "      <Codec Name=\"string\">\n" +
            "        <!--Optional:-->\n" +
            "        <Bandwidth>string</Bandwidth>\n" +
            "        <!--Optional:-->\n" +
            "        <MaxBandwidth>string</MaxBandwidth>\n" +
            "      </Codec>\n" +
            "    </Properties>\n" +
            "  </Start>\n" +
            "  <Update Type=\"string\">\n" +
            "    <!--Optional:-->\n" +
            "    <From>\n" +
            "      <!--Optional:-->\n" +
            "      <Id>string</Id>\n" +
            "      <!--Optional:-->\n" +
            "      <EPId>string</EPId>\n" +
            "      <URI>http://www.company.gov/ego/ni</URI>\n" +
            "      <!--Optional:-->\n" +
            "      <Contact>http://www.your.edu/ego/corde</Contact>\n" +
            "      <!--Optional:-->\n" +
            "      <IP>string</IP>\n" +
            "      <!--Optional:-->\n" +
            "      <Port>7</Port>\n" +
            "      <!--Optional:-->\n" +
            "      <EPType>string</EPType>\n" +
            "      <!--Optional:-->\n" +
            "      <Relay>anyType</Relay>\n" +
            "      <!--Optional:-->\n" +
            "      <RelayPort>anyType</RelayPort>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexiveIP>anyType</ReflexiveIP>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexivePort>anyType</ReflexivePort>\n" +
            "      <!--Optional:-->\n" +
            "      <UserAgent>string</UserAgent>\n" +
            "      <!--Optional:-->\n" +
            "      <IncallEnabled>false</IncallEnabled>\n" +
            "    </From>\n" +
            "    <!--Optional:-->\n" +
            "    <To>\n" +
            "      <!--Optional:-->\n" +
            "      <Id>string</Id>\n" +
            "      <!--Optional:-->\n" +
            "      <EPId>string</EPId>\n" +
            "      <URI>http://www.my.com/temperat/rapidum</URI>\n" +
            "      <!--Optional:-->\n" +
            "      <Contact>http://www.sample.gov/gero/altos</Contact>\n" +
            "      <!--Optional:-->\n" +
            "      <IP>string</IP>\n" +
            "      <!--Optional:-->\n" +
            "      <Port>7</Port>\n" +
            "      <!--Optional:-->\n" +
            "      <EPType>string</EPType>\n" +
            "      <!--Optional:-->\n" +
            "      <Relay>anyType</Relay>\n" +
            "      <!--Optional:-->\n" +
            "      <RelayPort>anyType</RelayPort>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexiveIP>anyType</ReflexiveIP>\n" +
            "      <!--Optional:-->\n" +
            "      <ReflexivePort>anyType</ReflexivePort>\n" +
            "      <!--Optional:-->\n" +
            "      <UserAgent>string</UserAgent>\n" +
            "      <!--Optional:-->\n" +
            "      <IncallEnabled>false</IncallEnabled>\n" +
            "    </To>\n" +
            "    <!--Optional:-->\n" +
            "    <Properties>\n" +
            "      <Protocol>string</Protocol>\n" +
            "      <!--Optional:-->\n" +
            "      <Bandwidth Multiplexed=\"3\">\n" +
            "        <!--Optional:-->\n" +
            "        <Average>10</Average>\n" +
            "        <!--Optional:-->\n" +
            "        <Maximum>10</Maximum>\n" +
            "      </Bandwidth>\n" +
            "      <!--Zero or more repetitions:-->\n" +
            "      <Codec Name=\"string\">\n" +
            "        <!--Optional:-->\n" +
            "        <Bandwidth>string</Bandwidth>\n" +
            "        <!--Optional:-->\n" +
            "        <MaxBandwidth>string</MaxBandwidth>\n" +
            "      </Codec>\n" +
            "    </Properties>\n" +
            "  </Update>\n" +
            "  <!--Optional:-->\n" +
            "  <Route>\n" +
            "    <!--1 or more repetitions:-->\n" +
            "    <Hop>string</Hop>\n" +
            "  </Route>\n" +
            "  <!--Optional:-->\n" +
            "  <Properties>\n" +
            "    <!--Optional:-->\n" +
            "    <ResponseCode Code=\"5\">string</ResponseCode>\n" +
            "    <!--Optional:-->\n" +
            "    <MSDiagnostics>string</MSDiagnostics>\n" +
            "    <!--Optional:-->\n" +
            "    <MSDiagnosticsClient>anyType</MSDiagnosticsClient>\n" +
            "    <!--Optional:-->\n" +
            "    <MSDiagnosticsPublic>anyType</MSDiagnosticsPublic>\n" +
            "  </Properties>\n" +
            "  <!--Optional:-->\n" +
            "  <RawSDP>string</RawSDP>\n" +
            "</LyncDiagnostics>";
}
